name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'

exclude-labels:
    - 'docs'
    - 'pedantic'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes

  $CHANGES
