# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: ShariffBundle
  description: This bundle provides a wrapper for using shariff inside the sonata-project.
  homepage: https://core23.de
  topics: symfony, symfony-bundle, bundle, php, shariff, sonata, sonata-block

branches:
  - name: master
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (7.4)"
          - "Static Code Analysis (7.4)"
          - "Tests (7.2, lowest)"
          - "Tests (7.2, highest)"
          - "Tests (7.3, lowest)"
          - "Tests (7.3, highest)"
          - "Tests (7.4, lowest)"
          - "Tests (7.4, highest)"
          - "Code Coverage (7.4)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
