vcs: git

prerequisites:
    - working-copy-check
    - display-last-changes
    - composer-json-check:
        composer: composer
    - composer-stability-check
    - command:
        cmd: composer outdated

pre-release-actions:
    changelog-update:
        format: simple
        dump-commits: true
        exclude-merge-commits: true

version-generator: semantic
version-persister: vcs-tag
