language: php

php:
  - 7.1
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TARGET=lint
    - php: 7.1
      env: TARGET=phpstan
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
  allow_failures:
    - php: nightly
    - php: 7.1
      env: TARGET=phpstan

install:
 - composer global require satooshi/php-coveralls sllh/composer-lint codeclimate/php-test-reporter --prefer-dist --no-interaction
 - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
 - if [ "$TARGET" == "phpstan" ]; then composer require --dev phpstan/phpstan:^0.8 --no-update; fi
 - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make $TARGET

after_script:
 - coveralls -v
 - test-reporter
